"""Add tipo_venta to VentaDiaria

Revision ID: 650007711ba1
Revises: 8b6a8d24ba91
Create Date: 2025-09-01 13:55:10.822072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650007711ba1'
down_revision = '8b6a8d24ba91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta_diaria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_venta', sa.String(length=50), nullable=False, server_default='DESPACHO'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta_diaria', schema=None) as batch_op:
        batch_op.drop_column('tipo_venta')

    # ### end Alembic commands ###
