"""Add precio_regular and precio_minimo to ProductoPanaderia and tipo_venta to VentaDiaria

Revision ID: 8b6a8d24ba91
Revises: 
Create Date: 2025-08-31 21:27:26.251166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b6a8d24ba91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto_panaderia', schema=None) as batch_op:
        # Add new columns as nullable first
        batch_op.add_column(sa.Column('precio_regular', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('precio_minimo', sa.Float(), nullable=True))

    # Use direct SQL to update data for existing rows
    op.execute('UPDATE producto_panaderia SET precio_regular = precio_venta')
    op.execute('UPDATE producto_panaderia SET precio_minimo = 0.0') # Or some other default like precio_regular

    with op.batch_alter_table('producto_panaderia', schema=None) as batch_op:
        # Drop the old column
        batch_op.drop_column('precio_venta')
        # Alter new columns to be non-nullable if desired (after data is populated)
        batch_op.alter_column('precio_regular', existing_type=sa.Float(), nullable=False)
        batch_op.alter_column('precio_minimo', existing_type=sa.Float(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto_panaderia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_venta', sa.FLOAT(), nullable=False))
        batch_op.drop_column('precio_minimo')
        batch_op.drop_column('precio_regular')

    # ### end Alembic commands ###
