"""agregar campos tipo_precio a clientes panaderia

Revision ID: c06b68385abb
Revises: 650007711ba1
Create Date: 2025-11-02 13:22:42.136391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c06b68385abb'
down_revision = '650007711ba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente_panaderia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_minimo', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('precio_regular', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('precio_regalia', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente_panaderia', schema=None) as batch_op:
        batch_op.drop_column('precio_regalia')
        batch_op.drop_column('precio_regular')
        batch_op.drop_column('precio_minimo')

    # ### end Alembic commands ###
